# Доступные зачеия Explorers:
# ClientLic - Клиентские лицензии
# AvailablePerformance - Доступная производительность (через RAC)
# SheduleJob - Проверка галки "блокировка регламентных заданий"
# Session - Сеансы
# Connect - Соединения
# SessionsData - различные показарели из консоли 1с  (через RAC)
# ProcData - Данные поцессов (получается из ОС, пока поддерживается только linux)
# CPU - загрузка ЦПУ
# disk - метрики дикска, пока только linux и WeightedIO
# Property - доп. свойства, у каждой метрики свои могут быть.
# у ProcData доп. свойство processes определяет список процессов которые нужно мониторить
# у всех метрик доп. свойство timerNotyfy время опроса в секундах (через какой интервал будут запрашиваться метрики). Если не задан по дефолту 10 сек.
Explorers:
  - Name: ClientLic
    Property:
      timerNotyfy: 60
  - Name: AvailablePerformance
    Property:
      timerNotyfy: 10
  - Name: CPU
    Property:
      timerNotyfy: 10
  - Name: disk
    Property:
      timerNotyfy: 10
  - Name: SheduleJob
    Property:
      timerNotyfy: 10
  - Name: Session
    Property:
      timerNotyfy: 60
  - Name: Connect
    Property:
      timerNotyfy: 60
  - Name: SessionsData
    Property:
      timerNotyfy: 10
  - Name: ProcData
    Property:
      processes:
        - rphost
        - ragent
        - rmngr
      timerNotyfy: 10
MSURL:         # Не обязательный параметр
MSUSER:        # Не обязательный параметр
MSPAS:         # Не обязательный параметр
RAC:
  Path: "C:\\Program Files\\1cv8\\8.3.15.1656\\bin\\rac.exe"
  Port: "1545"      # Не обязательный параметр
  Host: "sr-1c-main.holding.melonfashion.ru" # Не обязательный параметр
  Login: ""         # Не обязательный параметр
  Pass: ""          # Не обязательный параметр
LogDir: "c:\\log"  # Если на задан логи будут писаться в каталог с исполняемым файлом
LogLevel: 5                   # Уровень логирования от 2 до 6, где 2 - ошибка, 3 - предупреждение, 4 - информация, 5 - дебаг, 6 - трейс
TimeRotate: 1                 # Время в часах через которое будет создаваться новый файл логов
TTLLogs: 8                    # Время жизни логов в часах
